package com.bizaia.zhongyin.repository.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bizaia.zhongyin.repository.data.CoursewareBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COURSEWARE_BEAN".
*/
public class CoursewareBeanDao extends AbstractDao<CoursewareBean, Long> {

    public static final String TABLENAME = "COURSEWARE_BEAN";

    /**
     * Properties of entity CoursewareBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LiveId = new Property(1, long.class, "liveId", false, "LIVE_ID");
        public final static Property UserId = new Property(2, int.class, "userId", false, "USER_ID");
        public final static Property PdfUrl = new Property(3, String.class, "pdfUrl", false, "PDF_URL");
    }


    public CoursewareBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CoursewareBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COURSEWARE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LIVE_ID\" INTEGER NOT NULL ," + // 1: liveId
                "\"USER_ID\" INTEGER NOT NULL ," + // 2: userId
                "\"PDF_URL\" TEXT);"); // 3: pdfUrl
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COURSEWARE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CoursewareBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLiveId());
        stmt.bindLong(3, entity.getUserId());
 
        String pdfUrl = entity.getPdfUrl();
        if (pdfUrl != null) {
            stmt.bindString(4, pdfUrl);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CoursewareBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLiveId());
        stmt.bindLong(3, entity.getUserId());
 
        String pdfUrl = entity.getPdfUrl();
        if (pdfUrl != null) {
            stmt.bindString(4, pdfUrl);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CoursewareBean readEntity(Cursor cursor, int offset) {
        CoursewareBean entity = new CoursewareBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // liveId
            cursor.getInt(offset + 2), // userId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // pdfUrl
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CoursewareBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLiveId(cursor.getLong(offset + 1));
        entity.setUserId(cursor.getInt(offset + 2));
        entity.setPdfUrl(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CoursewareBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CoursewareBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CoursewareBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
